name: Fechamento B3

on:
  schedule:
    - cron: '15 21 * * 1-5'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  coleta:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: pip install yfinance pandas openpyxl

      - name: Executar coleta
        run: python coleta_fechamento.py

      - name: Salvar CSV no repositório
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Fechamento_Diario.csv
          git commit -m "Atualiza fechamento diário"
          git push
